# What is a Data Scientist? {#whatis}

One of the first questions that might have occurred to you as you've heard about data scientists is: What do they do?

This is actually not quite a simple answer. Data science has come to serve as a label for data specialists. They are able to approach a wide swath of problems due to their ability to work in data in all of its forms. Data scientists are master data manipulators. They are often well-versed in statistics, and they thrive on solving business problems with their skills.

## Data Manipulation and Programming
This expertise in data manipulation comes thanks to the toolkit at their disposal. Rather than relying on old proprietary software, or be limited by a graphical interface, data scientists almost always use programming languages to manipulate data. Because of the power and flexibility of these programming languages like *Python* and *R*, they're able to work with gigabytes of data with millions of rows as easily as they would work with ten rows. They aren't daunted by size. In fact, most data scientists I've met salivate over massive datasets, because more data gives them many more possibilities.

These programming languages are specialized to move data into and out of different environments and formats. A data scientist can pull data from the a hundred websites, combine the relevant information into one dataset and perform statistical analysis from there. Often, they spend a lot of time cleaning the dataset. They purge it of impurities, impute missing values and convert messy data into a beautiful tabular dataset. In fact, the saying goes that eighty percent of a data scientist's time is spent cleaning data.

Below is an example of a function that a data scientist might employ in order to manipulate the data, using the programming language *Python*. The particular function expands a dataset to include exponential transformations of its variables. It's an example of code that would be used to rapidly generate lots of different data from an existing dataset.

```python
def df_expansion(data_frame, order=2, interactions = False):
    # Creates empty dataframe
    # We will append our new columns into the df, and then
    # concatenate our new frame to the original
    new_df = pd.DataFrame()
    relevant_col_list = []
    
    
    def check_if_relevant(df):
        for col in df.columns:
            unique_vals = list(df[col].unique())
            if not (len(unique_vals) == 2 and 0 in unique_vals and 1 in unique_vals):
                relevant_col_list.append(col)
            
    check_if_relevant(data_frame)
    for exponent in (range(1,order)):
        exponent += 1 # For each exponent, add columns
        for col in relevant_col_list:
            new_df[col+'**'+str(exponent)] = data_frame[col]**exponent
    
    if interactions:
        for col1 in data_frame.columns:
            for col2 in data_frame.columns:
                if col1 != col2:
                    new_df[col1+"*"+col2] = data_frame[col1]*data_frame[col2]
    new_dataframe = pd.concat([data_frame, new_df], axis=1)
    return new_dataframe
```
Using code like the example above, they are able to rapidly evaluate large amounts of data in order to solve the problem at hand. Data that becomes difficult to manage in Excel is mincemeat for a data scientist. A typical day for a data scientist will involve an immense amount of data cleaning, and these skills should not be discounted.

## Statistical Knowledge
The common saying goes that data scientists know more computer science than a statistician, and more statistics than a computer scientist. While I'm not convinced this is very true, it does provide a useful heuristic to think about data scientists. Their ability to move data from A to B is an invaluable skill, however they often rely on statistical analysis and data visualization to extract usefulness from the data.

This is where the reported sexiness of a data scientist comes into play [CITATION]. With a deep knowledge of statistics, a data scientist is able to tease out patterns and relationships from the data they are analyzing. Some of the most well-known tools in their belt include *Machine Learning*, *Natural Language Processing*, *A/B Testing*, among many others. This is probably the most well-known part of the data scientist's skillset and the statistical concepts and ideas they employ will be the subject of most of this book.

## Solving Business Problems
A data scientist is not a theorist. They are practicioners with a large toolkit, looking to solve practical problems in the real world.

## Code
As I mentioned before, data scientists often solve their data problems using code. The advantages of doing so are numerous. Writing code allows the analyst to be incredible specific about what they want the computer to do for them. They can work with large amounts of data with the same ease as smaller tables. But by far, the biggest advantage of working with code is the transferability:

At the end of the day. The code that an individual writes is just text. It's merely a string of characters put together that, when put through the write interpreter, can command the computer to do certain specific things. We can easily download the same interpreter, and the code that you write should be just as good on my machine.

The ideas behind code are often incredibly powerful. Because of this, software was often kept private. While the format of the code is just text, the instructions that the machine executes can be invaluable, and are economically essential for a company to keep secret, lest they lose all exclusivity over the product.

But this is not the case for the Free and Open Source Movement. In fact, in the 1950's and 1960's, software was primarily written by academics who shared their code freely and openly. It wasn't until the 1970's and 1980's that software was generally closed off from the public.

Programming languages and their compilers are generally released as open-source software. Python and R are no exceptions. As mentioned before, Python and R are two of the most common programming languages for data science. A key step in the rise of these languages in data science comes from the fact that they are free and open-source. They are freely available for anyone to use and write code in. When statisticians (who flocked primarily to the R programming language) started writing their own packages--code wrapped into a bundle so as to be distributed--they shared them openly online. Their colleagues, or anyone who stumbled upon them, could use the code written and scrutinized by professionals in their field.

Over the years, the number of statistical packages on both Python and R have grown tremendously. Data scientists today have access to state of the art methods of data and statistical analysis, and they're not afraid to use them. Data scientists are able to reach for open-source software implementations of some of the most powerful techniques around today and implement them in almost no time. Their analysis stands on the shoulders of benevolent giants, to the benefit of everyone.

https://en.wikipedia.org/wiki/History_of_free_and_open-source_software
https://en.wikipedia.org/wiki/Open-source-software_movement
https://journal.r-project.org/archive/2009-1/RJournal_2009-1_Chambers.pdf 

